ALTER SESSION SET CONTAINER = PDBProject;
ALTER DATABASE OPEN;
create user ATBM identified by 123;
GRANT CREATE SESSION, CREATE TABLE, UNLIMITED TABLESPACE TO ATBM;
GRANT ALL PRIVILEGES TO ATBM;
GRANT SELECT ANY DICTIONARY TO ATBM;



create TABLE ATBM.NHANSU
(
    MANV VARCHAR2(10),
    HOTEN VARCHAR2(50),
    PHAI NVARCHAR2(5),
    NGSINH date,
    PHUCAP VARCHAR2(10),    
    DT VARCHAR2(10),
    VAITRO NVARCHAR2(50),
    MADV VARCHAR2(10),
    CONSTRAINT PK_NHANSU PRIMARY KEY (MANV)
);

CREATE TABLE ATBM.SINHVIEN
(
    MASV VARCHAR2(10),
    HOTEN VARCHAR2(50),
    PHAI VARCHAR2(5),
    NGSINH date,
    DIACHI VARCHAR2(50),
    DT VARCHAR2(10),
    MACT VARCHAR2(10),
    MANGANH VARCHAR2(10),
    SOTCTL number(4),
    DTBTL number(4,2),
    CONSTRAINT PK_SINHVIEN PRIMARY KEY (MASV)
);

CREATE TABLE ATBM.DONVI
(
    MADV VARCHAR2(10),
    TENDV NVARCHAR2(50),
    TRGDV VARCHAR(10),
    CONSTRAINT PK_DONVI PRIMARY KEY (MADV)
);

CREATE TABLE ATBM.HOCPHAN
(
    MAHP VARCHAR2(10),
    TENHP NVARCHAR2(50),
    SOTC NUMBER(2),
    STLT NUMBER(2),
    STTH NUMBER(2),
    SOSVTD NUMBER(3),
    MADV VARCHAR2(10),
    CONSTRAINT PK_HOCPHAN PRIMARY KEY (MAHP)
);



CREATE TABLE ATBM.KHMO
(
    MAHP VARCHAR2(10),
    HK VARCHAR2(10),
    NAM VARCHAR(10),
    MACT VARCHAR2(10),
    CONSTRAINT PK_KHMO PRIMARY KEY (MAHP,HK,NAM,MACT)
);

CREATE TABLE ATBM.PHANCONG
(
    MAGV VARCHAR2(10),
    MAHP VARCHAR2(10),
    HK VARCHAR2(10),
    NAM VARCHAR(10),
    MACT VARCHAR2(10),
    CONSTRAINT PK_KHMM PRIMARY KEY (MAGV,MAHP,HK,NAM,MACT)
);

CREATE TABLE ATBM.DANGKY
(
    MASV VARCHAR2(10),
    MAGV VARCHAR2(10),
    MAHP VARCHAR2(10),
    HK VARCHAR2(10),
    NAM VARCHAR2(10),
    MACT VARCHAR2(10),
    DIEMTH NUMBER(4,2),
    DIEMQT NUMBER(4,2),
    DIEMCK NUMBER(4,2),
    DIEMTK NUMBER(4,2),
    CONSTRAINT PK_DANGKY PRIMARY KEY (MASV,MAGV,MAHP,HK,NAM,MACT)
);

ALTER TABLE ATBM.NHANSU ADD CONSTRAINT FK_NHANSU_MADV FOREIGN KEY (MADV) REFERENCES ATBM.DONVI(MADV);
ALTER TABLE ATBM.HOCPHAN ADD CONSTRAINT FK_HOCPHAN_MADV FOREIGN KEY (MADV) REFERENCES ATBM.DONVI(MADV);
ALTER TABLE ATBM.KHMO ADD CONSTRAINT FK_KHMO_MAHP FOREIGN KEY (MAHP) REFERENCES ATBM.HOCPHAN(MAHP);
ALTER TABLE ATBM.PHANCONG ADD CONSTRAINT FK_PHANCONG_MAGV FOREIGN KEY (MAGV) REFERENCES ATBM.NHANSU(MANV);
ALTER TABLE ATBM.PHANCONG ADD CONSTRAINT FK_PHANCONG_MAHP FOREIGN KEY (MAHP) REFERENCES ATBM.HOCPHAN(MAHP);
ALTER TABLE ATBM.DANGKY ADD CONSTRAINT FK_DANGKY_MASV FOREIGN KEY (MASV) REFERENCES ATBM.SINHVIEN(MASV);
ALTER TABLE ATBM.DANGKY ADD CONSTRAINT FK_DANGKY_MAGV FOREIGN KEY (MAGV) REFERENCES ATBM.NHANSU(MANV);
ALTER TABLE ATBM.DANGKY ADD CONSTRAINT FK_DANGKY_MAHP FOREIGN KEY (MAHP) REFERENCES ATBM.HOCPHAN(MAHP);







